{
  "hash": "24427f923309eeccea58a9583ec05816",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Verify the Claim: Option A\"\nauthor: \"Rutong Chen\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-summary: \"Show code\"\n    embed-resources: true\n---\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# this chunk stays visible\n```\n:::\n\n\n\n\n## Part 1 — Reconstruct\n\nThe article compares the 2006–2010 and 2013–2017 American Community Survey (ACS) five-year estimates. I use `B17001_002` for the estimated number of people below the poverty level and `B17001_001` for the population whose poverty status was determined. Dividing the first estimate by the second gives a poverty rate. I use ACS five-year data because those are the periods identified in the article and because tract-level data are available. The periods do not overlap: one ends in 2010 and the other begins in 2013.\n\nThe article reports figures for neighborhoods such as Eastwick and Fairhill but does not identify which census tracts it assigned to each neighborhood. I therefore analyze Philadelphia census tracts. I assume the same ACS poverty definition can be used in both periods. My tract results describe geographic patterns in the city; they cannot reproduce the article's exact neighborhood estimates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_vars <- c(\n  total = \"B17001_001\",\n  below = \"B17001_002\"\n)\n\nget_poverty <- function(yr) {\n  get_acs(\n    geography = \"tract\",\n    variables = poverty_vars,\n    state = \"PA\",\n    county = \"Philadelphia\",\n    year = yr,\n    survey = \"acs5\",\n    output = \"wide\"\n  ) %>%\n    mutate(period = paste0(yr - 4, \"-\", yr))\n}\n\npoverty_2010 <- get_poverty(2010)\npoverty_2017 <- get_poverty(2017)\n```\n:::\n\n\n## Part 2 — Test\n\nFor each tract, I calculate the poverty rate and use `moe_prop()` to calculate the margin of error (MOE) of that rate. The MOE of the poverty count cannot simply be used as the MOE of the rate. I then calculate the coefficient of variation (CV) from the rate's standard error. I classify CV values below 12% as reliable, 12%–40% as somewhat reliable, and above 40% as unreliable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalculate_rate <- function(data) {\n  data %>%\n    mutate(\n      rate = case_when(\n        totalE > 0 ~ belowE / totalE,\n        TRUE ~ NA_real_\n      ),\n      rate_moe = case_when(\n        totalE > 0 ~ moe_prop(belowE, totalE, belowM, totalM),\n        TRUE ~ NA_real_\n      ),\n      cv = case_when(\n        rate > 0 ~ (rate_moe / 1.645) / rate * 100,\n        TRUE ~ NA_real_\n      ),\n      reliability = case_when(\n        is.na(cv) ~ \"Unavailable\",\n        cv < 12 ~ \"Reliable\",\n        cv <= 40 ~ \"Somewhat reliable\",\n        TRUE ~ \"Unreliable\"\n      )\n    )\n}\n\npoverty_2010 <- calculate_rate(poverty_2010)\npoverty_2017 <- calculate_rate(poverty_2017)\n\npoverty_2017 %>%\n  count(reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  reliability           n\n  <chr>             <int>\n1 Reliable             22\n2 Somewhat reliable   332\n3 Unavailable           8\n4 Unreliable           22\n```\n\n\n:::\n:::\n\n\nThe two periods contain 384 tracts each. In 2013–2017, 22 tract estimates are reliable under the CV rule, 332 are somewhat reliable, 22 are unreliable, and 8 have no calculable rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_wide <- bind_rows(\n  poverty_2010,\n  poverty_2017\n) %>%\n  select(GEOID, NAME, period, rate, rate_moe) %>%\n  pivot_wider(\n    names_from = period,\n    values_from = c(rate, rate_moe)\n  )\n\npoverty_tested <- poverty_wide %>%\n  mutate(\n    change = `rate_2013-2017` - `rate_2006-2010`,\n    se_1 = `rate_moe_2006-2010` / 1.645,\n    se_2 = `rate_moe_2013-2017` / 1.645,\n    se_diff = sqrt(se_1^2 + se_2^2),\n    moe_diff = se_diff * 1.645,\n    significant = abs(change) > moe_diff,\n    change_pp = change * 100,\n    moe_diff_pp = moe_diff * 100\n  )\n\npoverty_tested %>%\n  count(significant)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  significant     n\n  <lgl>       <int>\n1 FALSE         313\n2 TRUE           63\n3 NA              8\n```\n\n\n:::\n:::\n\n\nOf the 376 tracts with usable rates in both periods, 63 show a statistically detectable change at the 90% confidence level: 36 increased and 27 decreased. The other 313 do not show a detectable change. Eight tracts cannot be tested because their poverty-status population is zero in at least one period, making the rate undefined. I leave these eight in the data as missing values and exclude them only from calculations that require a rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_2010 %>%\n  summarize(zero_denominators = sum(totalE == 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  zero_denominators\n              <int>\n1                 7\n```\n\n\n:::\n\n```{.r .cell-code}\npoverty_2017 %>%\n  summarize(zero_denominators = sum(totalE == 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  zero_denominators\n              <int>\n1                 8\n```\n\n\n:::\n\n```{.r .cell-code}\npoverty_tested %>%\n  filter(!is.na(significant)) %>%\n  summarize(\n    detectable_increases = sum(significant & change > 0),\n    detectable_decreases = sum(significant & change < 0)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  detectable_increases detectable_decreases\n                 <int>                <int>\n1                   36                   27\n```\n\n\n:::\n:::\n\n\n### Changes and their uncertainty\n\nThe bars below show the 15 largest *estimated* increases. An error bar that crosses zero means that its change is not detectable at the 90% confidence level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_tested %>%\n  filter(!is.na(significant)) %>%\n  arrange(desc(change_pp)) %>%\n  slice_head(n = 15) %>%\n  mutate(\n    NAME = str_remove(\n      NAME,\n      \", Philadelphia County, Pennsylvania\"\n    )\n  ) %>%\n  ggplot(aes(x = reorder(NAME, change_pp), y = change_pp)) +\n  geom_col(fill = \"steelblue\") +\n  geom_errorbar(\n    aes(\n      ymin = change_pp - moe_diff_pp,\n      ymax = change_pp + moe_diff_pp\n    ),\n    width = 0.3\n  ) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  coord_flip() +\n  theme_minimal() +\n  labs(\n    title = \"Largest estimated increases in tract poverty rates\",\n    subtitle = \"2006–2010 to 2013–2017 ACS; error bars show 90% MOE\",\n    x = NULL,\n    y = \"Change in poverty rate (percentage points)\"\n  )\n```\n\n::: {.cell-output-display}\n![Estimated poverty-rate changes and 90% margins of error for the 15 tracts with the largest estimated increases.](assignment3_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n### A second view of the changes\n\nEach point below represents one tract. Color indicates whether its change is detectable at the 90% confidence level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_tested %>%\n  filter(!is.na(significant)) %>%\n  ggplot(\n    aes(\n      x = `rate_2006-2010` * 100,\n      y = change_pp,\n      color = significant\n    )\n  ) +\n  geom_point() +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  theme_minimal() +\n  labs(\n    title = \"Poverty changes vary across Philadelphia tracts\",\n    subtitle = \"2006–2010 to 2013–2017 ACS\",\n    x = \"2006–2010 poverty rate (%)\",\n    y = \"Change (percentage points)\",\n    color = \"Detectable change\"\n  )\n```\n\n::: {.cell-output-display}\n![Earlier poverty rate and later change for Philadelphia tracts with calculable rates in both periods.](assignment3_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n### Reliability table\n\nThis table shows five examples from each CV category. It is a sample of tracts, not the complete list.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreliability_table <- poverty_2017 %>%\n  filter(!is.na(cv)) %>%\n  arrange(desc(cv)) %>%\n  group_by(reliability) %>%\n  slice_head(n = 5) %>%\n  ungroup() %>%\n  mutate(\n    dot = case_when(\n      cv < 12 ~ \"🟢\",\n      cv <= 40 ~ \"🟡\",\n      TRUE ~ \"🔴\"\n    ),\n    NAME = str_remove(\n      NAME,\n      \", Philadelphia County, Pennsylvania\"\n    ),\n    rate_pct = rate * 100,\n    moe_pp = rate_moe * 100\n  ) %>%\n  select(dot, NAME, rate_pct, moe_pp, cv, reliability)\n\nreliability_table %>%\n  gt() %>%\n  fmt_number(\n    columns = c(rate_pct, moe_pp, cv),\n    decimals = 1\n  ) %>%\n  cols_label(\n    dot = \"\",\n    NAME = \"Tract\",\n    rate_pct = \"Poverty rate (%)\",\n    moe_pp = \"Rate MOE (points)\",\n    cv = \"CV (%)\",\n    reliability = \"Reliability\"\n  ) %>%\n  cols_align(align = \"center\", columns = dot) %>%\n  tab_header(\n    title = \"Reliability of tract poverty-rate estimates\",\n    subtitle = \"Philadelphia, 2013–2017 ACS; five examples per category\"\n  ) %>%\n  tab_source_note(\n    \"CV = (rate MOE / 1.645) / rate × 100. Jurjevich et al. (2018) thresholds: <12% reliable; 12–40% somewhat reliable; >40% unreliable.\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"crnlrceinh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#crnlrceinh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#crnlrceinh thead, #crnlrceinh tbody, #crnlrceinh tfoot, #crnlrceinh tr, #crnlrceinh td, #crnlrceinh th {\n  border-style: none;\n}\n\n#crnlrceinh p {\n  margin: 0;\n  padding: 0;\n}\n\n#crnlrceinh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#crnlrceinh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#crnlrceinh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#crnlrceinh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#crnlrceinh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#crnlrceinh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#crnlrceinh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#crnlrceinh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#crnlrceinh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#crnlrceinh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#crnlrceinh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#crnlrceinh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#crnlrceinh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#crnlrceinh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#crnlrceinh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#crnlrceinh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#crnlrceinh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#crnlrceinh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#crnlrceinh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#crnlrceinh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#crnlrceinh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#crnlrceinh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#crnlrceinh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#crnlrceinh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#crnlrceinh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#crnlrceinh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#crnlrceinh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#crnlrceinh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#crnlrceinh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#crnlrceinh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#crnlrceinh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#crnlrceinh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#crnlrceinh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#crnlrceinh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#crnlrceinh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#crnlrceinh .gt_left {\n  text-align: left;\n}\n\n#crnlrceinh .gt_center {\n  text-align: center;\n}\n\n#crnlrceinh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#crnlrceinh .gt_font_normal {\n  font-weight: normal;\n}\n\n#crnlrceinh .gt_font_bold {\n  font-weight: bold;\n}\n\n#crnlrceinh .gt_font_italic {\n  font-style: italic;\n}\n\n#crnlrceinh .gt_super {\n  font-size: 65%;\n}\n\n#crnlrceinh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#crnlrceinh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#crnlrceinh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#crnlrceinh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#crnlrceinh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#crnlrceinh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#crnlrceinh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#crnlrceinh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#crnlrceinh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal\" style>Reliability of tract poverty-rate estimates</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Philadelphia, 2013–2017 ACS; five examples per category</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dot\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"NAME\">Tract</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rate_pct\">Poverty rate (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"moe_pp\">Rate MOE (points)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cv\">CV (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"reliability\">Reliability</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 91</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">50.8</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">10.0</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 122.01</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">32.0</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">6.3</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 162</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">47.6</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">9.3</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 369</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">45.1</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">8.8</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 178</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">56.5</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">10.8</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 352</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">5.9</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">3.9</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">40.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 10.01</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">5.9</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">3.9</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">39.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 40.02</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">7.2</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">4.7</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">39.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 12.01</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">3.0</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">2.0</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">39.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 385</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">7.0</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">4.5</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">39.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 9891</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">92.5</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">220.4</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">144.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 9800</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">4.9</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">7.0</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">85.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 231</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">0.8</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">0.8</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">66.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 256</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">3.6</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">3.9</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">64.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"NAME\" class=\"gt_row gt_left\">Census Tract 9801</td>\n<td headers=\"rate_pct\" class=\"gt_row gt_right\">13.3</td>\n<td headers=\"moe_pp\" class=\"gt_row gt_right\">13.4</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">61.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"6\">CV = (rate MOE / 1.645) / rate × 100. Jurjevich et al. (2018) thresholds: &lt;12% reliable; 12–40% somewhat reliable; &gt;40% unreliable.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Part 3 — Adjudicate\n\n**Supported.** The article describes Philadelphia's 2013–2017 poverty rate as approximately 26%. A separate ACS estimate for Philadelphia County is 25.8%, which rounds to 26%. The tract results also show that poverty rates increased detectably in some parts of the city: 36 tracts show an increase at the 90% confidence level.\n\n**Not supported by this test.** A broad reading that poverty rose dramatically across Philadelphia as a whole goes further than these tract results show. Only 36 of 376 comparable tracts show a detectable increase; 27 show a detectable decrease, and 313 show no detectable change. This does not disprove an increase in any particular neighborhood. **Cannot be determined:** The article's exact figures for Eastwick, Fairhill, and Holmesburg cannot be checked with this tract analysis because the article does not provide its tract-to-neighborhood boundaries. Its claim about *white* poverty also requires race-specific data, which the overall poverty variables here do not measure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_city_rate <- function(yr) {\n  get_acs(\n    geography = \"county\",\n    variables = poverty_vars,\n    state = \"PA\",\n    county = \"Philadelphia\",\n    year = yr,\n    survey = \"acs5\",\n    output = \"wide\"\n  ) %>%\n    mutate(\n      period = paste0(yr - 4, \"-\", yr),\n      rate = belowE / totalE,\n      rate_moe = moe_prop(belowE, totalE, belowM, totalM)\n    )\n}\n\ncity_rates <- bind_rows(\n  get_city_rate(2010),\n  get_city_rate(2017)\n)\n\ncity_rates %>%\n  mutate(\n    poverty_rate_pct = rate * 100,\n    rate_moe_pp = rate_moe * 100\n  ) %>%\n  select(period, poverty_rate_pct, rate_moe_pp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  period    poverty_rate_pct rate_moe_pp\n  <chr>                <dbl>       <dbl>\n1 2006-2010             25.1       0.541\n2 2013-2017             25.8       0.460\n```\n\n\n:::\n:::\n\n\n## Part 4 — Rewrite\n\nPhiladelphia's 2013–2017 ACS puts the city's poverty rate at about 26%. Across its census tracts, the pattern of change is mixed. Compared with 2006–2010, 36 tracts had a detectable increase in poverty rates, while 27 had a detectable decrease. In another 313 tracts, the estimated change was too uncertain to distinguish from zero at the 90% confidence level. These tract results cannot confirm the article's precise figures for named neighborhoods, because the article does not identify which tracts it used to define them.\n",
    "supporting": [
      "assignment3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}