{
  "hash": "e979ba2f45da60c4661440e538cfa50f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Rutong Chen\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n---\n\n## The question\n\nEvery number published by the American Community Survey is an estimate based on\na sample rather than a complete count. Each estimate therefore comes with a\nmargin of error that describes its statistical uncertainty.\n\nIn this analysis, I examine median gross rent across counties in New York State\nand ask which communities are measured most and least reliably. Understanding\nthe uncertainty in rent estimates is important because these data may influence\nhousing policy and the allocation of affordable housing resources.\n\n---\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"NY\"\nmy_variable <- \"B25064_001\"\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                         variable   estimate   moe\n  <chr> <chr>                        <chr>         <dbl> <dbl>\n1 36001 Albany County, New York      B25064_001     1252    22\n2 36003 Allegany County, New York    B25064_001      754    33\n3 36005 Bronx County, New York       B25064_001     1436    11\n4 36007 Broome County, New York      B25064_001      914    26\n5 36009 Cattaraugus County, New York B25064_001      759    30\n6 36011 Cayuga County, New York      B25064_001      895    39\n```\n\n\n:::\n:::\n\n\nThe dataset contains 62 rows, with one observation for each county-level unit in\nNew York State. This matches the 62 counties and county equivalents in the\nstate.\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 100 dollars means something different for an estimate of\n800 dollars than for an estimate of 2,000 dollars. To compare uncertainty across\ncounties, I calculate the margin of error as a percentage of the estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\nNow I sort the counties to identify the least reliable estimates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                        estimate   moe moe_pct\n   <chr>                          <dbl> <dbl>   <dbl>\n 1 Hamilton County, New York        860    95   11.0 \n 2 Schuyler County, New York        858    75    8.74\n 3 Greene County, New York          993    79    7.96\n 4 Lewis County, New York           821    59    7.19\n 5 Orleans County, New York         877    60    6.84\n 6 Yates County, New York           802    46    5.74\n 7 Wyoming County, New York         782    44    5.63\n 8 Cortland County, New York        911    50    5.49\n 9 Chenango County, New York        819    44    5.37\n10 Livingston County, New York      912    48    5.26\n```\n\n\n:::\n:::\n\n\nHamilton County has the largest margin of error relative to its estimate. Its\nestimated median gross rent is 860 dollars, with a margin of error of 95 dollars.\nThe margin of error is therefore approximately 11.0 percent of the estimate.\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    51\n2 Low confidence      1\n3 Moderate           10\n```\n\n\n:::\n:::\n\n\nUsing these thresholds, 51 counties are classified as high confidence, 10 as\nmoderate, and one as low confidence. These thresholds are analytical categories\nused to compare counties in this report rather than official Census Bureau\nstandards.\n\n---\n\n## Is the margin of error bigger in small places?\n\nTo compare the reliability of the rent estimate with county population, I pull\nmedian gross rent and total population together in wide format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                         myvarE myvarM    popE  popM\n  <chr> <chr>                         <dbl>  <dbl>   <dbl> <dbl>\n1 36001 Albany County, New York        1252     22  315374    NA\n2 36003 Allegany County, New York       754     33   47027    NA\n3 36005 Bronx County, New York         1436     11 1419250    NA\n4 36007 Broome County, New York         914     26  197738    NA\n5 36009 Cattaraugus County, New York    759     30   76479    NA\n6 36011 Cayuga County, New York         895     39   75464    NA\n```\n\n\n:::\n:::\n\n\nThe `E` suffix identifies an estimate, while the `M` suffix identifies its\nmargin of error. Therefore, `myvarE` and `myvarM` contain the median gross rent\nestimate and margin of error, while `popE` and `popM` contain the corresponding\npopulation values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow I compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         51        381479.\n2 Low confidence           1          5102 \n3 Moderate                10         41178.\n```\n\n\n:::\n:::\n\n\nHigh-confidence counties have an average population of approximately 381,479,\ncompared with approximately 41,178 in moderate-confidence counties. Hamilton\nCounty, the only low-confidence county, has an estimated population of 5,102.\nThis pattern suggests that counties with smaller populations tend to have less\nprecise median gross rent estimates. It is consistent with the smaller ACS\nsamples generally available in less populated places.\n\n---\n\n## What this means for policy\n\nThe results show that Hamilton County is the New York county we know the least\nabout for median gross rent. Its estimated median gross rent is \\$860, with a\nmargin of error of \\$95, or about 11.0 percent of the estimate. It is the only\ncounty classified as low confidence under the thresholds used here. Schuyler\nand Greene Counties also have relatively large margins of error, at\napproximately 8.7 percent and 8.0 percent, respectively, and are classified as\nmoderate confidence.\n\nThis pattern is related to the way the American Community Survey works. The ACS\nis based on a sample rather than a complete count of every household. Counties\nwith smaller populations generally provide fewer sampled households, so their\nestimates tend to be less precise. In this analysis, high-confidence counties\nhave an average population of about 381,479, compared with about 41,178 for\nmoderate-confidence counties and 5,102 for the low-confidence county. These\nresults are consistent with the expectation that smaller places are measured\nwith greater uncertainty.\n\nIgnoring this uncertainty could create unfair policy outcomes. If New York\nState allocated affordable-housing funds using median rent estimates alone,\nHamilton County could be treated as though its estimate were just as precise as\nestimates for much larger counties. A county near a funding threshold might\nreceive too little assistance, or be excluded entirely, because of sampling\nvariation rather than a genuine difference in housing needs. Agencies should\ntherefore consider both the estimate and its margin of error, especially when\nmaking decisions about small rural communities.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}